headers:
  description: "Creates the IAM roles, groups aso. for this app."
  runWhen: "#{not @instance.profiles().contains('test')}"
  onCommandError: IGNORE

pipeline:

  - iam.run.as:
      username: "systemuser"

  - iam.role.create:
      name: "CAN_APP_EXTERNALINVOICEFORM"

  - iam.role.add.composites:
      roleName: "CAN_APP_EXTERNALINVOICEFORM"
      composites: "CAN_PIPE_property.schema.put, CAN_PIPE_property.move, CAN_PIPE_event.listen, CAN_RUN_AS_SOURCE"

  - iam.role.add.composites:
      roleName: "ROLE_SUPPORT"
      composites: "CAN_APP_EXTERNALINVOICEFORM"

  - iam.role.add.composites:
      roleName: "ROLE_DEVELOPER"
      composites: "CAN_APP_EXTERNALINVOICEFORM"

  - iam.role.add.composites:
      roleName: "ROLE_ADMIN"
      composites: "CAN_APP_EXTERNALINVOICEFORM"

  - iam.role.add.composites:
      roleName: "ROLE_EMPLOYEE"
      composites: "CAN_APP_EXTERNALINVOICEFORM"
