pipeline:
  - event.listen:
      key: "property.created"
      filter: "#{body.target.key.contains('global/app/sickleaveform/object/sickleaveform/v1/instance')}"
  - property.send.delivery:
      key: "#{body.target.key}"
      message: "uri:property:global/app/sickleaveform/template/sickleaveform-message"
      subject: "Formular Krankmeldung wurde ausgefüllt"
      model: "uri:property:#{body.target.key}"
      privacyLevel: "L02_CREDENTIALS"
      recipients:
        - "#{@property.lazy('global/app/sickleaveform/config/sickleaveform#recipient')}"