vars:
  config: "#{@property.value('global/app/weclapp/config/app').config}"

pipeline:

  - event.listen:
      key: "property.created"
      filter: "#{body.target.key.contains('global/app/weclapp/object/article-action/v1/instance') and body.target.value.action == 'block'}"

  - iam.run.as:
      username: systemuser

  - http.post:
      url: "https://#{vars.config.wclTenantId}.weclapp.com/webapp/api/v1/warehouseStockMovement/bookTransferMovement"
      headers: "AuthenticationToken: #{vars.config.wclAuthenticationToken}"
      body: |
        {
          "articleId": "#{vars.config.wclDefaultArticleId}",
          "quantity": "1",
          "sourceWarehouseLevelId": "#{vars.config.wclMainWarehouseLevelId}",
          "targetWarehouseLevelId": "#{vars.config.wclReservationWarehouseLevelId}",
          "serialNumbers": [
            "#{body.target.value.serialNumber}"
          ]
        }
